# Series and DataFrames in Pandas

Pandas provides two main data structures:

- Series
- DataFrame

These structures allow analysts to work with labeled and structured data efficiently.

A Series represents a single column of data, while a DataFrame represents a complete table composed of multiple Series.

Understanding these structures is essential because most real-world datasets are stored as DataFrames.

# Pandas Series

A Series is a one-dimensional labeled array.

It can store:

- Numbers
- Text
- Dates
- Other Python objects

Each value has an associated index, which allows efficient data selection.

## Creating a Series

### From a Python list

In [2]:
import pandas as pd

sales = pd.Series(
    [100, 200, 300, 400]
)

print(sales)

0    100
1    200
2    300
3    400
dtype: int64

By default, Pandas creates an automatic numerical index starting from 0.

The index identifies each value in the Series.

### Custom Index

In [3]:
sales = pd.Series(
    [100, 200, 300, 400],
    index=[
        "January",
        "February",
        "March",
        "April"
    ]
)

print(sales)

January     100
February    200
March       300
April       400
dtype: int64

A custom index can make data easier to understand.

In business analytics, labels are often more meaningful than numerical indexes.

## Accessing Series values

### Using index

In [4]:
sales["March"]

300

### Using position

In [5]:
sales.iloc[2]

300

There are two common ways to access data:

- Label-based selection → `.loc[]`
- Position-based selection → `.iloc[]`

## Series attributes

In [23]:
print("Values:")
print(sales.values)


print("\nIndex:")
print(sales.index)


print("\nData type:")
print(sales.dtype)

Values:
[100 200 300 400]

Index:
Index(['January', 'February', 'March', 'April'], dtype='object')

Data type:
int64

## Series methods

### Basic statistics

In [24]:
sales.sum()

1000

In [25]:
sales.mean()

250.0

In [26]:
sales.max()

400

In [27]:
sales.min()

100

Series objects include many methods for data analysis.

These methods are frequently used when calculating business metrics.

# Pandas DataFrame

A DataFrame is a two-dimensional data structure organized into rows and columns.

It is similar to a spreadsheet or a SQL table.

Each column in a DataFrame is a Pandas Series.

Example:

Customer database:

| Customer | Age | City |
|---|---|---|
| Ana | 25 | Madrid |
| Luis | 32 | Barcelona |

## Creating a DataFrame

### From dictionary

In [8]:
data = {
    "Product": [
        "Laptop",
        "Phone",
        "Tablet"
    ],
    
    "Price": [
        1200,
        800,
        500
    ],
    
    "Stock": [
        10,
        25,
        15
    ]
}


df = pd.DataFrame(data)


print(df)

  Product  Price  Stock
0  Laptop   1200     10
1   Phone    800     25
2  Tablet    500     15

## DataFrame structure

In [9]:
df.shape

(3, 3)

`shape` returns:

(rows, columns)

In this example:

- 3 rows
- 3 columns

## Columns

### List column names

In [10]:
df.columns

Index(['Product', 'Price', 'Stock'], dtype='object')

### Select a column

In [11]:
df["Product"]

0    Laptop
1     Phone
2    Tablet
Name: Product, dtype: object

Selecting a single column returns a Series.

### Select multiple columns

In [12]:
df[
    [
        "Product",
        "Price"
    ]
]

  Product  Price
0  Laptop   1200
1   Phone    800
2  Tablet    500

Selecting multiple columns returns another DataFrame.

## Rows

### First rows

In [13]:
df.head()

  Product  Price  Stock
0  Laptop   1200     10
1   Phone    800     25
2  Tablet    500     15

### Last rows

In [14]:
df.tail()

  Product  Price  Stock
0  Laptop   1200     10
1   Phone    800     25
2  Tablet    500     15

In [ ]:
## Selecting rows with index

### loc

In [15]:
df.loc[0]

Product    Laptop
Price        1200
Stock          10
Name: 0, dtype: object

`.loc[]` selects data using labels.

It is useful when working with named indexes.

### iloc

In [16]:
df.iloc[0]

Product    Laptop
Price        1200
Stock          10
Name: 0, dtype: object

`.iloc[]` selects data using numerical positions.

It works like Python list indexing.

## Selecting specific values

### loc example

In [17]:
df.loc[0, "Product"]

'Laptop'

### iloc example

In [18]:
df.iloc[0, 0]

'Laptop'

## Adding columns

New columns can be created using existing information.

In [19]:
df["Total Value"] = (
    df["Price"] *
    df["Stock"]
)

print(df)

  Product  Price  Stock  Total Value
0  Laptop   1200     10        12000
1   Phone    800     25        20000
2  Tablet    500     15         7500

## Removing columns

In [20]:
df.drop(
    columns=[
        "Stock"
    ]
)

  Product  Price  Total Value
0  Laptop   1200        12000
1   Phone    800        20000
2  Tablet    500         7500

## DataFrame information

### info()

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Product      3 non-null      object
 1   Price        3 non-null      int64
 2   Stock        3 non-null      int64
 3   Total Value  3 non-null      int64
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes

### describe()

In [22]:
df.describe()

             Price      Stock   Total Value
count     3.000000   3.000000      3.000000
mean    833.333333  16.666667  13166.666667
std     351.188458   7.637626   6331.139971
min     500.000000  10.000000   7500.000000
25%     650.000000  12.500000   9750.000000
50%     800.000000  15.000000  12000.000000
75%    1000.000000  20.000000  16000.000000
max    1200.000000  25.000000  20000.000000

These methods provide a quick overview of the dataset:

`info()`

- Column names
- Data types
- Missing values


`describe()`

- Count
- Mean
- Standard deviation
- Minimum
- Maximum

# Relationship between Series and DataFrame

A DataFrame is made of multiple Series.

Example:

Product column:

Series

Price column:

Series

Stock column:

Series


Together they create a DataFrame.

In [23]:
type(df["Product"])

pandas.core.series.Series

# Business Example: Store Sales

A company stores information about its products.

We want to calculate the revenue generated by each product.

In [24]:
sales_data = {
    "Product":[
        "Laptop",
        "Phone",
        "Tablet",
        "Monitor"
    ],
    
    "Units Sold":[
        15,
        30,
        20,
        12
    ],
    
    "Price":[
        1200,
        800,
        500,
        300
    ]
}


sales_df = pd.DataFrame(
    sales_data
)


print(sales_df)

   Product  Units Sold  Price
0   Laptop          15   1200
1    Phone          30    800
2   Tablet          20    500
3  Monitor          12    300

In [25]:
sales_df["Revenue"] = (
    sales_df["Units Sold"] *
    sales_df["Price"]
)

print(sales_df)

   Product  Units Sold  Price  Revenue
0   Laptop          15   1200    18000
1    Phone          30    800    24000
2   Tablet          20    500    10000
3  Monitor          12    300     3600

---

##  Practice Exercises

### Exercise 1

Create a Series containing the monthly revenue of a company:

January: 5000
February: 7000
March: 6500
April: 8000

Calculate:

- Total revenue
- Average revenue
- Best month

In [ ]:
# Write your solution here

### Exercise 2

Create a DataFrame with:

Product
Category
Price
Quantity

Then:

- Create a Revenue column
- Show the products with revenue above average

In [ ]:
# Write your solution here

### Exercise 3

Create a customer DataFrame:

Customer
Age
Country
Purchases

Answer:

- What is the average age?
- Which customer has the highest purchases?
- How many customers are from each country?

In [ ]:
# Write your solution here

## Solutions

In [33]:
# Solution 1

monthly_revenue = pd.Series(
    [5000, 7000, 6500, 8000], 
    index=[
        "January",
        "February",
        "March",
        "April"
    ]
)

print(monthly_revenue)

print(f"Total revenue: {monthly_revenue.sum():,.2f} €")
print(f"Average revenue: {monthly_revenue.mean():,.2f} €")
print(f"Best month: {monthly_revenue.idxmax()}")
print(f"Highest revenue: {monthly_revenue.max():,.2f} €")

January     5000
February    7000
March       6500
April       8000
dtype: int64
Total revenue: 26,500.00 €
Average revenue: 6,625.00 €
Best month: April
Highest revenue: 8,000.00 €

In [ ]:
# Solution 2

home_decor = {
    "Product": [
        "Ceramic Vase",
        "Wall Mirror",
        "Table Lamp",
        "Cushion Cover",
        "Wooden Shelf",
        "Scented Candle"
    ],
    "Category": [
        "Decor",
        "Wall Decor",
        "Lighting",
        "Textiles",
        "Furniture",
        "Home Fragrance"
    ],
    "Price": [
        35.99,
        89.50,
        59.90,
        18.99,
        74.95,
        12.50
    ],
    "Quantity": [
        25,
        10,
        18,
        40,
        12,
        50
    ]
}

decor_df = pd.DataFrame(home_decor)

decor_df["Revenue"] = (
    decor_df["Price"] *
    decor_df["Quantity"]
) 

print(decor_df)

average_revenue = decor_df["Revenue"].mean()

print(f"\nAverage revenue: {average_revenue}")

print("\nProducts above average revenue:")

print(
    decor_df[
        decor_df["Revenue"] > average_revenue
    ]
)

          Product        Category  Price  Quantity  Revenue
0    Ceramic Vase           Decor  35.99        25   899.75
1     Wall Mirror      Wall Decor  89.50        10   895.00
2      Table Lamp        Lighting  59.90        18  1078.20
3   Cushion Cover        Textiles  18.99        40   759.60
4    Wooden Shelf       Furniture  74.95        12   899.40
5  Scented Candle  Home Fragrance  12.50        50   625.00

Average revenue: 859.4916666666667

Products above average revenue:
        Product    Category  Price  Quantity  Revenue
0  Ceramic Vase       Decor  35.99        25   899.75
1   Wall Mirror  Wall Decor  89.50        10   895.00
2    Table Lamp    Lighting  59.90        18  1078.20
4  Wooden Shelf   Furniture  74.95        12   899.40

In [48]:
# Solution 3

customers = {
    "Customer": [
        "Alice",
        "Bob",
        "Charlie",
        "Diana",
        "Emma"
    ],
    
    "Age": [
        25,
        34,
        29,
        41,
        31
    ],
    
    "Country": [
        "Spain",
        "France",
        "Spain",
        "Germany",
        "Spain"
    ],
    
    "Purchases": [
        1200,
        950,
        1800,
        700,
        1500
    ]
}

customers_df = pd.DataFrame(customers)

print(customers_df)

average_age = customers_df["Age"].mean()

print(f"\nAverage age: {average_age}")

highest_purchase = customers_df.loc[
    customers_df["Purchases"].idxmax()
    ]

print(f"\nCustomer with highest purchases:")
print(highest_purchase)

print("\nCustomers by country:")
print(customers_df["Country"].value_counts())

  Customer  Age  Country  Purchases
0    Alice   25    Spain       1200
1      Bob   34   France        950
2  Charlie   29    Spain       1800
3    Diana   41  Germany        700
4     Emma   31    Spain       1500

Average age: 32.0

Customer with highest purchases:
Customer     Charlie
Age               29
Country        Spain
Purchases       1800
Name: 2, dtype: object

Customers by country:
Country
Spain      3
France     1
Germany    1
Name: count, dtype: int64