# Loading and Exploring Data

One of the first tasks of a Data Analyst is loading and understanding a dataset.

Before performing any analysis, it is essential to explore the data to understand:

- Dataset size
- Available columns
- Data types
- Missing values
- General statistics

This initial exploration helps identify potential data quality issues and guides the next steps of the analysis.

In [15]:
import pandas as pd

# Loading Data

Pandas can read many different file formats.

The most common ones in Data Analytics are:

- CSV
- Excel
- JSON

### CSV

In [16]:
df = pd.read_csv("../../datasets/sales.csv")

### Excel

In [42]:
df = pd.read_excel("sales.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'sales.xlsx'

### JSON

df = pd.read_json("sales.json")

The `read_*()` functions create a DataFrame directly from external files.

CSV is the most common format used in analytics projects.

# Exploring the dataset

### head()

In [ ]:
df.head()

         Date   Product     Category Region  Price  Quantity  Revenue
0  2026-01-01    Laptop  Electronics  North   1200         5     6000
1  2026-01-02     Phone  Electronics  South    800         8     6400
2  2026-01-03    Tablet  Electronics   East    500         6     3000
3  2026-01-04   Monitor  Accessories   West    300        10     3000
4  2026-01-05  Keyboard  Accessories  North     50        20     1000

### head(10)

In [ ]:
df.head(10)

         Date   Product     Category Region  Price  Quantity  Revenue
0  2026-01-01    Laptop  Electronics  North   1200         5     6000
1  2026-01-02     Phone  Electronics  South    800         8     6400
2  2026-01-03    Tablet  Electronics   East    500         6     3000
3  2026-01-04   Monitor  Accessories   West    300        10     3000
4  2026-01-05  Keyboard  Accessories  North     50        20     1000
5  2026-01-06     Mouse  Accessories  South     30        25      750
6  2026-01-07    Laptop  Electronics   East   1200         4     4800
7  2026-01-08     Phone  Electronics   West    800         7     5600
8  2026-01-09    Tablet  Electronics  North    500         5     2500
9  2026-01-10   Monitor  Accessories  South    300         8     2400

### tail()

In [ ]:
df.tail()

         Date  Product     Category Region  Price  Quantity  Revenue
5  2026-01-06    Mouse  Accessories  South     30        25      750
6  2026-01-07   Laptop  Electronics   East   1200         4     4800
7  2026-01-08    Phone  Electronics   West    800         7     5600
8  2026-01-09   Tablet  Electronics  North    500         5     2500
9  2026-01-10  Monitor  Accessories  South    300         8     2400

### sample()

In [ ]:
df.sample(5)

         Date  Product     Category Region  Price  Quantity  Revenue
0  2026-01-01   Laptop  Electronics  North   1200         5     6000
3  2026-01-04  Monitor  Accessories   West    300        10     3000
8  2026-01-09   Tablet  Electronics  North    500         5     2500
5  2026-01-06    Mouse  Accessories  South     30        25      750
2  2026-01-03   Tablet  Electronics   East    500         6     3000

`sample()` returns random rows.

It is useful when working with very large datasets.

# Understanding the dataset

### shape

In [18]:
df.shape

(10, 7)

Returns:

(rows, columns)

### columns

In [19]:
df.columns

Index(['Date', 'Product', 'Category', 'Region', 'Price', 'Quantity',
       'Revenue'],
      dtype='object')

### index

In [20]:
df.index

RangeIndex(start=0, stop=10, step=1)

### dtypes

In [21]:
df.dtypes

Date        object
Product     object
Category    object
Region      object
Price        int64
Quantity     int64
Revenue      int64
dtype: object

### info()

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      10 non-null     object
 1   Product   10 non-null     object
 2   Category  10 non-null     object
 3   Region    10 non-null     object
 4   Price     10 non-null     int64
 5   Quantity  10 non-null     int64
 6   Revenue   10 non-null     int64
dtypes: int64(3), object(4)
memory usage: 692.0+ bytes

`info()` provides:

- Number of rows
- Number of columns
- Data types
- Missing values
- Memory usage

It is one of the first methods used by data analysts when working with a new dataset.

# Descriptive statistics

### describe()

In [23]:
df.describe()

            Price   Quantity      Revenue
count    10.00000  10.000000    10.000000
mean    568.00000   9.800000  3545.000000
std     423.89202   7.020605  2034.760428
min      30.00000   4.000000   750.000000
25%     300.00000   5.250000  2425.000000
50%     500.00000   7.500000  3000.000000
75%     800.00000   9.500000  5400.000000
max    1200.00000  25.000000  6400.000000

`describe()` summarizes numerical columns by calculating:

- Count
- Mean
- Standard deviation
- Minimum
- Quartiles
- Maximum

### nunique()

In [24]:
df.nunique()

Date        10
Product      6
Category     2
Region       4
Price        6
Quantity     8
Revenue      9
dtype: int64

### value_counts()

In [25]:
df["Category"].value_counts()

Category
Electronics    6
Accessories    4
Name: count, dtype: int64

# Missing values overview

### isnull()

In [26]:
df.isnull()

    Date  Product  Category  Region  Price  Quantity  Revenue
0  False    False     False   False  False     False    False
1  False    False     False   False  False     False    False
2  False    False     False   False  False     False    False
3  False    False     False   False  False     False    False
4  False    False     False   False  False     False    False
5  False    False     False   False  False     False    False
6  False    False     False   False  False     False    False
7  False    False     False   False  False     False    False
8  False    False     False   False  False     False    False
9  False    False     False   False  False     False    False

### Count missing values

In [27]:
df.isnull().sum()

Date        0
Product     0
Category    0
Region      0
Price       0
Quantity    0
Revenue     0
dtype: int64

Missing values are common in real-world datasets.

Before performing any analysis, analysts should identify columns containing missing data.

# Business Example

In [28]:
sales_df = pd.read_csv("../../datasets/sales.csv")

In [29]:
sales_df.head()

         Date   Product     Category Region  Price  Quantity  Revenue
0  2026-01-01    Laptop  Electronics  North   1200         5     6000
1  2026-01-02     Phone  Electronics  South    800         8     6400
2  2026-01-03    Tablet  Electronics   East    500         6     3000
3  2026-01-04   Monitor  Accessories   West    300        10     3000
4  2026-01-05  Keyboard  Accessories  North     50        20     1000

In [30]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      10 non-null     object
 1   Product   10 non-null     object
 2   Category  10 non-null     object
 3   Region    10 non-null     object
 4   Price     10 non-null     int64
 5   Quantity  10 non-null     int64
 6   Revenue   10 non-null     int64
dtypes: int64(3), object(4)
memory usage: 692.0+ bytes

In [31]:
sales_df.describe()

            Price   Quantity      Revenue
count    10.00000  10.000000    10.000000
mean    568.00000   9.800000  3545.000000
std     423.89202   7.020605  2034.760428
min      30.00000   4.000000   750.000000
25%     300.00000   5.250000  2425.000000
50%     500.00000   7.500000  3000.000000
75%     800.00000   9.500000  5400.000000
max    1200.00000  25.000000  6400.000000

In [32]:
sales_df["Category"].value_counts()

Category
Electronics    6
Accessories    4
Name: count, dtype: int64

In [33]:
sales_df.isnull().sum()

Date        0
Product     0
Category    0
Region      0
Price       0
Quantity    0
Revenue     0
dtype: int64

From this initial exploration we can identify:

- Dataset dimensions
- Available variables
- Data types
- Possible missing values
- Distribution of categorical variables

These observations guide the data cleaning process before analysis.

---

##  Practice Exercises

### Exercise 1

Load a CSV dataset.

Display:

- first five rows
- last five rows
- shape
- columns

In [ ]:
# Write your solution here

### Exercise 2

Explore a dataset.

Calculate:

- number of rows
- number of columns
- data types
- descriptive statistics

In [ ]:
# Write your solution here

### Exercise 3

Using the sales dataset:

Find:

- number of unique categories

- products per category

- missing values

- average product price

In [ ]:
# Write your solution here

### Extra Challenge

Using the **sales.csv** dataset:

1. Calculate the total revenue for each product.
2. Create a new column called **Revenue**.
3. Find the product with the highest revenue.
4. Calculate the total company revenue.
5. Display only the products whose revenue is above the average.

In [ ]:
# Write your solution here

## Solutions

In [38]:
# Solution 1

import pandas as pd

# Load the dataset

sales_df = pd.read_csv("../../datasets/sales.csv")

# Display the first five rows
print("First five rows:")
print(sales_df.head())

# Display the last five rows
print("\nLast five rows:")
print(sales_df.tail())

# Dataset dimensions
print("\nDataset shape:")
print(sales_df.shape)

# Column names
print("\nColumns:")
print(sales_df.columns)

First five rows:
         Date   Product     Category Region  Price  Quantity  Revenue
0  2026-01-01    Laptop  Electronics  North   1200         5     6000
1  2026-01-02     Phone  Electronics  South    800         8     6400
2  2026-01-03    Tablet  Electronics   East    500         6     3000
3  2026-01-04   Monitor  Accessories   West    300        10     3000
4  2026-01-05  Keyboard  Accessories  North     50        20     1000

Last five rows:
         Date  Product     Category Region  Price  Quantity  Revenue
5  2026-01-06    Mouse  Accessories  South     30        25      750
6  2026-01-07   Laptop  Electronics   East   1200         4     4800
7  2026-01-08    Phone  Electronics   West    800         7     5600
8  2026-01-09   Tablet  Electronics  North    500         5     2500
9  2026-01-10  Monitor  Accessories  South    300         8     2400

Dataset shape:
(10, 7)

Columns:
Index(['Date', 'Product', 'Category', 'Region', 'Price', 'Quantity',
       'Revenue'],
      dtype='object')

In [39]:
# Solution 2

import pandas as pd

# Load the dataset

sales_df = pd.read_csv("../../datasets/sales.csv")

# Number of rows and columns
rows, columns = sales_df.shape

print(f"Rows: {rows}")
print(f"Columns: {columns}")

# Data types
print("\nData types:")
print(sales_df.dtypes)

# Dataset information
print("\nDataset information:")
sales_df.info()

# Descriptive statistics
print("\nDescriptive statistics:")
print(sales_df.describe())

Rows: 10
Columns: 7

Data types:
Date        object
Product     object
Category    object
Region      object
Price        int64
Quantity     int64
Revenue      int64
dtype: object

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      10 non-null     object
 1   Product   10 non-null     object
 2   Category  10 non-null     object
 3   Region    10 non-null     object
 4   Price     10 non-null     int64
 5   Quantity  10 non-null     int64
 6   Revenue   10 non-null     int64
dtypes: int64(3), object(4)
memory usage: 692.0+ bytes

Descriptive statistics:
            Price   Quantity      Revenue
count    10.00000  10.000000    10.000000
mean    568.00000   9.800000  3545.000000
std     423.89202   7.020605  2034.760428
min      30.00000   4.000000   750.000000
25%     300.00000   5.250000  2425.000000
50%     500.00000   7.500000  3000.000000
75%     800.00000   9.500000  5400.000000
max    1200.00000  25.000000  6400.000000

In [ ]:
# Solution 3

In [40]:
import pandas as pd

# Load the dataset
sales_df = pd.read_csv("../../datasets/sales.csv")

# Number of unique categories
print("Unique categories:")
print(sales_df["Category"].nunique())

# Products per category
print("\nProducts per category:")
print(sales_df["Category"].value_counts())

# Missing values
print("\nMissing values:")
print(sales_df.isnull().sum())

# Average product price
print("\nAverage product price:")
print(sales_df["Price"].mean())

Unique categories:
2

Products per category:
Category
Electronics    6
Accessories    4
Name: count, dtype: int64

Missing values:
Date        0
Product     0
Category    0
Region      0
Price       0
Quantity    0
Revenue     0
dtype: int64

Average product price:
568.0

In [41]:
# Extra Challenge

import pandas as pd

# Load the dataset
sales_df = pd.read_csv("../../datasets/sales.csv")

# Create a new Revenue column
sales_df["Revenue"] = sales_df["Price"] * sales_df["Quantity"]

print(sales_df)

# Product with the highest revenue
highest_revenue = sales_df.loc[sales_df["Revenue"].idxmax()]

print("\nProduct with highest revenue:")
print(highest_revenue)

# Total revenue
print("\nTotal revenue:")
print(sales_df["Revenue"].sum())

# Average revenue
average_revenue = sales_df["Revenue"].mean()

print("\nAverage revenue:")
print(average_revenue)

# Products above average revenue
print("\nProducts above average revenue:")
print(sales_df[sales_df["Revenue"] > average_revenue])

         Date   Product     Category Region  Price  Quantity  Revenue
0  2026-01-01    Laptop  Electronics  North   1200         5     6000
1  2026-01-02     Phone  Electronics  South    800         8     6400
2  2026-01-03    Tablet  Electronics   East    500         6     3000
3  2026-01-04   Monitor  Accessories   West    300        10     3000
4  2026-01-05  Keyboard  Accessories  North     50        20     1000
5  2026-01-06     Mouse  Accessories  South     30        25      750
6  2026-01-07    Laptop  Electronics   East   1200         4     4800
7  2026-01-08     Phone  Electronics   West    800         7     5600
8  2026-01-09    Tablet  Electronics  North    500         5     2500
9  2026-01-10   Monitor  Accessories  South    300         8     2400

Product with highest revenue:
Date         2026-01-02
Product           Phone
Category    Electronics
Region            South
Price               800
Quantity              8
Revenue            6400
Name: 1, dtype: object

Total revenue:
35450

Average revenue:
3545.0

Products above average revenue:
         Date Product     Category Region  Price  Quantity  Revenue
0  2026-01-01  Laptop  Electronics  North   1200         5     6000
1  2026-01-02   Phone  Electronics  South    800         8     6400
6  2026-01-07  Laptop  Electronics   East   1200         4     4800
7  2026-01-08   Phone  Electronics   West    800         7     5600