# Data Selection and Filtering

After loading a dataset, the next step is selecting the information that is relevant for the analysis.

Pandas provides powerful tools to:

- Select specific columns
- Select rows
- Filter data based on conditions
- Sort values
- Find unique values

These operations are among the most frequently used in real-world Data Analytics projects.

In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv("../../datasets/customers.csv")

customers.head()

   CustomerID Customer  Country  Age   Segment
0           1    Alice    Spain   28   Premium
1           2      Bob   France   35  Standard
2           3  Charlie  Germany   42   Premium
3           4    Diana    Italy   31  Standard
4           5     Emma    Spain   26   Premium

# Selecting Columns

Columns can be selected using square brackets.

Selecting one column returns a Series.

Selecting multiple columns returns a DataFrame.

### Single column

In [35]:
customers["Customer"]

0      Alice
1        Bob
2    Charlie
3      Diana
4       Emma
5      Lucas
6      Sofia
7       Noah
Name: Customer, dtype: object

### Multiple columns

In [36]:
customers[
    [
        "Customer",
        "Country",
        "Age"
    ]
]

  Customer   Country  Age
0    Alice     Spain   28
1      Bob    France   35
2  Charlie   Germany   42
3    Diana     Italy   31
4     Emma     Spain   26
5    Lucas  Portugal   39
6    Sofia     Spain   33
7     Noah    France   29

### Column type

In [37]:
type(customers["Customer"])

pandas.core.series.Series

In [38]:
type(
    customers[
        [
            "Customer",
            "Country"
        ]
    ]
)

pandas.core.frame.DataFrame

# Selecting Rows

### First rows

In [39]:
customers.head()

   CustomerID Customer  Country  Age   Segment
0           1    Alice    Spain   28   Premium
1           2      Bob   France   35  Standard
2           3  Charlie  Germany   42   Premium
3           4    Diana    Italy   31  Standard
4           5     Emma    Spain   26   Premium

### Last rows

In [40]:
customers.tail()

   CustomerID Customer   Country  Age   Segment
3           4    Diana     Italy   31  Standard
4           5     Emma     Spain   26   Premium
5           6    Lucas  Portugal   39  Standard
6           7    Sofia     Spain   33   Premium
7           8     Noah    France   29  Standard

### Random rows

In [41]:
customers.sample(5)

   CustomerID Customer  Country  Age   Segment
7           8     Noah   France   29  Standard
2           3  Charlie  Germany   42   Premium
1           2      Bob   France   35  Standard
4           5     Emma    Spain   26   Premium
0           1    Alice    Spain   28   Premium

# Using loc[]

## Label-based Selection

`.loc[]` selects rows and columns using labels.

Syntax:

```python
df.loc[row_label, column_label]
```

### Select one row

In [42]:
customers.loc[0]

CustomerID          1
Customer        Alice
Country         Spain
Age                28
Segment       Premium
Name: 0, dtype: object

### Select multiple rows

In [43]:
customers.loc[0:3]

   CustomerID Customer  Country  Age   Segment
0           1    Alice    Spain   28   Premium
1           2      Bob   France   35  Standard
2           3  Charlie  Germany   42   Premium
3           4    Diana    Italy   31  Standard

### Select one value

In [44]:
customers.loc[0, "Customer"]

'Alice'

### Select multiple columns

In [45]:
customers.loc[
    :,
    [
        "Customer",
        "Country"
    ]
]

  Customer   Country
0    Alice     Spain
1      Bob    France
2  Charlie   Germany
3    Diana     Italy
4     Emma     Spain
5    Lucas  Portugal
6    Sofia     Spain
7     Noah    France

# Using iloc

## Position-based Selection

`.iloc[]` selects rows and columns using integer positions.

### First row

In [46]:
customers.iloc[0]

CustomerID          1
Customer        Alice
Country         Spain
Age                28
Segment       Premium
Name: 0, dtype: object

### First three rows

In [47]:
customers.iloc[0:3]

   CustomerID Customer  Country  Age   Segment
0           1    Alice    Spain   28   Premium
1           2      Bob   France   35  Standard
2           3  Charlie  Germany   42   Premium

### Row and column

In [48]:
customers.iloc[
    0,
    2
]

'Spain'

### Multiple rows and columns

In [49]:
customers.iloc[
    0:4,
    1:3
]

  Customer  Country
0    Alice    Spain
1      Bob   France
2  Charlie  Germany
3    Diana    Italy

### loc vs iloc

| Method | Uses |
|---------|------|
| loc | Labels |
| iloc | Integer positions |

Remember:

- `loc` → names
- `iloc` → numbers

# Boolean Filtering

Filtering allows analysts to keep only the rows that satisfy specific conditions.

This is one of the most common operations in Pandas.

### Customers older than 30

In [50]:
customers[
    customers["Age"] > 30
]

   CustomerID Customer   Country  Age   Segment
1           2      Bob    France   35  Standard
2           3  Charlie   Germany   42   Premium
3           4    Diana     Italy   31  Standard
5           6    Lucas  Portugal   39  Standard
6           7    Sofia     Spain   33   Premium

### Customers from Spain

In [51]:
customers[
    customers["Country"] == "Spain"
]

   CustomerID Customer Country  Age  Segment
0           1    Alice   Spain   28  Premium
4           5     Emma   Spain   26  Premium
6           7    Sofia   Spain   33  Premium

### Multiple filters

### AND

In [52]:
customers[
    (customers["Country"] == "Spain") &
    (customers["Age"] > 30)
]

   CustomerID Customer Country  Age  Segment
6           7    Sofia   Spain   33  Premium

### OR

In [53]:
customers[
    (customers["Country"] == "Spain") |
    (customers["Country"] == "France")
]

   CustomerID Customer Country  Age   Segment
0           1    Alice   Spain   28   Premium
1           2      Bob  France   35  Standard
4           5     Emma   Spain   26   Premium
6           7    Sofia   Spain   33   Premium
7           8     Noah  France   29  Standard

### NOT

In [54]:
customers[
    customers["Country"] != "Spain"
]

   CustomerID Customer   Country  Age   Segment
1           2      Bob    France   35  Standard
2           3  Charlie   Germany   42   Premium
3           4    Diana     Italy   31  Standard
5           6    Lucas  Portugal   39  Standard
7           8     Noah    France   29  Standard

# isin()

`isin()` checks whether values belong to a list.

It is much cleaner than chaining multiple OR conditions.

In [55]:
customers[
    customers["Country"].isin(
        [
            "Spain",
            "France"
        ]
    )
]

   CustomerID Customer Country  Age   Segment
0           1    Alice   Spain   28   Premium
1           2      Bob  France   35  Standard
4           5     Emma   Spain   26   Premium
6           7    Sofia   Spain   33   Premium
7           8     Noah  France   29  Standard

# Sorting

### Sort by Age (Ascending)

In [56]:
customers.sort_values("Age")

   CustomerID Customer   Country  Age   Segment
4           5     Emma     Spain   26   Premium
0           1    Alice     Spain   28   Premium
7           8     Noah    France   29  Standard
3           4    Diana     Italy   31  Standard
6           7    Sofia     Spain   33   Premium
1           2      Bob    France   35  Standard
5           6    Lucas  Portugal   39  Standard
2           3  Charlie   Germany   42   Premium

### Sort by Age (Descending)

In [57]:
customers.sort_values(
    "Age",
    ascending=False
)

   CustomerID Customer   Country  Age   Segment
2           3  Charlie   Germany   42   Premium
5           6    Lucas  Portugal   39  Standard
1           2      Bob    France   35  Standard
6           7    Sofia     Spain   33   Premium
3           4    Diana     Italy   31  Standard
7           8     Noah    France   29  Standard
0           1    Alice     Spain   28   Premium
4           5     Emma     Spain   26   Premium

### Sort by Country and Age

In [58]:
customers.sort_values(
    by=["Segment", "Age"],
    ascending=[True, False]
)

   CustomerID Customer   Country  Age   Segment
2           3  Charlie   Germany   42   Premium
6           7    Sofia     Spain   33   Premium
0           1    Alice     Spain   28   Premium
4           5     Emma     Spain   26   Premium
5           6    Lucas  Portugal   39  Standard
1           2      Bob    France   35  Standard
3           4    Diana     Italy   31  Standard
7           8     Noah    France   29  Standard

# Unique Values

### unique()

In [3]:
customers["Country"].unique()

array(['Spain', 'France', 'Germany', 'Italy', 'Portugal'], dtype=object)

### nunique()

In [4]:
customers["Country"].nunique()

5

### value_counts()

In [5]:
customers["Country"].value_counts()

Country
Spain       3
France      2
Germany     1
Italy       1
Portugal    1
Name: count, dtype: int64

These methods help analysts understand categorical variables.

They are especially useful during Exploratory Data Analysis (EDA).

# Business Example

A company wants to analyze its customer database to answer the following questions:

- Customers from Spain
- Which customers belong to the Premium segment?
- Which customers are over 30 years old?
- How are customers distributed by country?
- Which countries have the largest customer base?

### Spanish customers

In [6]:
spain = customers[
    customers["Country"] == "Spain"
]

print(spain)

   CustomerID Customer Country  Age  Segment
0           1    Alice   Spain   28  Premium
4           5     Emma   Spain   26  Premium
6           7    Sofia   Spain   33  Premium

### Premium Customers

In [7]:
premium = customers[
    customers["Segment"] == "Premium"
]

print(premium)

   CustomerID Customer  Country  Age  Segment
0           1    Alice    Spain   28  Premium
2           3  Charlie  Germany   42  Premium
4           5     Emma    Spain   26  Premium
6           7    Sofia    Spain   33  Premium

### Customers Older Than 30

In [8]:
customers[
    customers["Age"] > 30
]

   CustomerID Customer   Country  Age   Segment
1           2      Bob    France   35  Standard
2           3  Charlie   Germany   42   Premium
3           4    Diana     Italy   31  Standard
5           6    Lucas  Portugal   39  Standard
6           7    Sofia     Spain   33   Premium

### Customers by Country

In [9]:
customers["Country"].value_counts()

Country
Spain       3
France      2
Germany     1
Italy       1
Portugal    1
Name: count, dtype: int64

### Customers by Segment

In [10]:
customers["Segment"].value_counts()

Segment
Premium     4
Standard    4
Name: count, dtype: int64

### Sort Customers by Age

In [11]:
customers.sort_values(
    "Age",
    ascending=False
)

   CustomerID Customer   Country  Age   Segment
2           3  Charlie   Germany   42   Premium
5           6    Lucas  Portugal   39  Standard
1           2      Bob    France   35  Standard
6           7    Sofia     Spain   33   Premium
3           4    Diana     Italy   31  Standard
7           8     Noah    France   29  Standard
0           1    Alice     Spain   28   Premium
4           5     Emma     Spain   26   Premium

These operations help companies:

- Identify customer segments.
- Understand customer demographics.
- Analyze market distribution.
- Prepare data for marketing campaigns.

---

##  Practice Exercises

### Exercise 1

Using the customers dataset:

- Display only the Customer column.
- Display Customer and Country.
- Show the first three rows.

In [ ]:
# Write your solution here

### Exercise 2

Find:

- Customers older than 30.
- Customers from Spain.
- Premium customers.

In [ ]:
# Write your solution here

### Exercise 3

Sort the dataset:

- By Age (ascending).
- By Country.
- By Segment and Age.

In [ ]:
# Write your solution here

### Exercise 4

Answer the following questions:

- How many different countries are represented?
- Which country has the most customers?
- How many Premium customers are there?
- Which Premium customers are older than 30?

## Solutions

In [13]:
# Solution 1

print(customers["Customer"])

print(
    customers[
        [
            "Customer",
            "Country"
        ]
    ]
)

print(customers.head(3))

0      Alice
1        Bob
2    Charlie
3      Diana
4       Emma
5      Lucas
6      Sofia
7       Noah
Name: Customer, dtype: object
  Customer   Country
0    Alice     Spain
1      Bob    France
2  Charlie   Germany
3    Diana     Italy
4     Emma     Spain
5    Lucas  Portugal
6    Sofia     Spain
7     Noah    France
   CustomerID Customer  Country  Age   Segment
0           1    Alice    Spain   28   Premium
1           2      Bob   France   35  Standard
2           3  Charlie  Germany   42   Premium

In [14]:
# Solution 2

print(
    customers[
        customers["Age"] > 30
    ]
)

print(
    customers[
        customers["Country"] == "Spain"
    ]
)

print(
    customers[
        customers["Segment"] == "Premium"
    ]
)

   CustomerID Customer   Country  Age   Segment
1           2      Bob    France   35  Standard
2           3  Charlie   Germany   42   Premium
3           4    Diana     Italy   31  Standard
5           6    Lucas  Portugal   39  Standard
6           7    Sofia     Spain   33   Premium
   CustomerID Customer Country  Age  Segment
0           1    Alice   Spain   28  Premium
4           5     Emma   Spain   26  Premium
6           7    Sofia   Spain   33  Premium
   CustomerID Customer  Country  Age  Segment
0           1    Alice    Spain   28  Premium
2           3  Charlie  Germany   42  Premium
4           5     Emma    Spain   26  Premium
6           7    Sofia    Spain   33  Premium

In [15]:
# Solution 3

print(customers.sort_values("Age"))

print(customers.sort_values("Country"))

print(
    customers.sort_values(
        by=["Segment", "Age"],
        ascending=[True, True]
    )
)

   CustomerID Customer   Country  Age   Segment
4           5     Emma     Spain   26   Premium
0           1    Alice     Spain   28   Premium
7           8     Noah    France   29  Standard
3           4    Diana     Italy   31  Standard
6           7    Sofia     Spain   33   Premium
1           2      Bob    France   35  Standard
5           6    Lucas  Portugal   39  Standard
2           3  Charlie   Germany   42   Premium
   CustomerID Customer   Country  Age   Segment
1           2      Bob    France   35  Standard
7           8     Noah    France   29  Standard
2           3  Charlie   Germany   42   Premium
3           4    Diana     Italy   31  Standard
5           6    Lucas  Portugal   39  Standard
0           1    Alice     Spain   28   Premium
4           5     Emma     Spain   26   Premium
6           7    Sofia     Spain   33   Premium
   CustomerID Customer   Country  Age   Segment
4           5     Emma     Spain   26   Premium
0           1    Alice     Spain   28   Premium
6           7    Sofia     Spain   33   Premium
2           3  Charlie   Germany   42   Premium
7           8     Noah    France   29  Standard
3           4    Diana     Italy   31  Standard
1           2      Bob    France   35  Standard
5           6    Lucas  Portugal   39  Standard

In [16]:
# Solution 4

print("Number of countries:")
print(customers["Country"].nunique())

print("\nCustomers by country:")
print(customers["Country"].value_counts())

print("\nPremium customers:")
print(
    customers["Segment"].value_counts()["Premium"]
)

print("\nPremium customers older than 30:")
print(
    customers[
        (customers["Segment"] == "Premium") &
        (customers["Age"] > 30)
    ]
)

Number of countries:
5

Customers by country:
Country
Spain       3
France      2
Germany     1
Italy       1
Portugal    1
Name: count, dtype: int64

Premium customers:
4

Premium customers older than 30:
   CustomerID Customer  Country  Age  Segment
2           3  Charlie  Germany   42  Premium
6           7    Sofia    Spain   33  Premium